### ISSUE TITLE
Issue with UITableViewCell

### ISSUE THREAD

**Issue by pinkal** [abiaad/PASImageView#13]
Hi,
I have a custom cell with PASImageView, the issue is when i scrolls the table view the previous cell's image is displayed and then the correct image is displayed.
Eg. There is 8 rows visible in the tableview, now when i scroll the 9th row will display image of the 1st row and after 1-2 second the correct image is displayed. Means progress for the 9th row is not visible. Can you help me for this?

Thanks.

**Comment by pinkal** [comment]
Anyone has solution for this? Its urgent.

**Comment by abiaad** [comment]
Sorry but I don't have time.
Did you try to debug your problem (by setting breakpoints etc ...) ?
