### ISSUE TITLE
Reset loaded image to placeholder one 

### ISSUE THREAD

**Issue by engmsaleh** [abiaad/PASImageView#16]
I'm using `PASImageView` as ImageView for avatar in my App. I display a placeholder image when the user didn't login and load the image when user login ... Thats all work fine.

But is there is a way to reset the image to the placeholder one when the user logout ?

**Comment by abiaad** [comment]
Not at this time. You can init a new instance to erase the old one.

**Comment by engmsaleh** [comment]
@abiaad Thanks a lot for quick reply 👍 , I have make the `containerImageView` property public and set it directly instead.
