### ISSUE TITLE
Unable to add from storyboard

### ISSUE THREAD

**Issue by arshu-dev** [abiaad/PASImageView#6]
If I add the view from storyboard it does not load the image. It only works when initialised by code.

**Comment by cloudjanak** [comment]
same problem

**Comment by abiaad** [comment]
I don't have time. Feel free to make pull requests. That's why this component is open source. Everyone should contribute.

**Comment by cloudjanak** [comment]
i dont have sound knowledge of this , can you please make this possible?

**Comment by abiaad** [comment]
Perhaps you should learn to read before asking questions. You also forgot "please" or "thanks". 
Seriously ...

**Comment by joshhensley** [comment]
It's a simple code change to allow for storyboard support. I have tested and it is working. Copy the initialization code in **override init(frame: CGRect)** (excluding the call to super.init) and place it in **required init?(coder aDecoder: NSCoder)** after the super.init call.

**Comment by abiaad** [comment]
Done for swift-2.0 branch.
