### ISSUE TITLE
Image URL Invalid

### ISSUE THREAD

**Issue by pinkal** [abiaad/PASImageView#9]
Hi, its great plugin.
I am loading image url. The image url is valid but image not exists.
So in this case the placeholder image is displayed but the progresslayer not updating. Progresslayer remains in redcolor.
So what additional action need to perform?

Thanks.

**Comment by abiaad** [comment]
Cannot reproduce your problem. What's your URL ?

**Comment by pinkal** [comment]
I have moved image to another folder and i was using old image url, so the old url will load with null data. But the progress layer remains in redcolor as URLSession's "downTask didFinishDownloadingToURL" is called.
my image is on local server (as this issue will not occur but if some url will be with null data)

Thanks.

**Comment by abiaad** [comment]
I commited some changes. See if it works now.

**Comment by pinkal** [comment]
Its working, thanks for quick reply.
